#Copyright 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stedi-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stedi-prod
  template:
    metadata:
      labels:
        app: stedi-prod
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"    
      containers:
        - name: stedi-prod
          image: gcr.io/cubs-consulting/stedi
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-prod
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-prod"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: twilio-dev
                  key: twilio_account_sid
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twilio-dev
                  key: twilio_token
            - name: TWILIO_PHONE
              value: "+17146778438"
            - name: TWILIO_SECTOR_MESSAGE_SID
              value: HX5350683922e94938e46721bda849ae42
            - name: TWILIO_OTP_MESSAGE_SID
              value: HX6ff75f1bb3d8d34962f20121cd369c18
          # The ports is a list of tcp ports the pod listens on
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: stedi-tcp-prod
spec:
  selector:
    app: stedi-prod
  ports:
    - protocol: TCP
      port: 54321
      targetPort: 54321
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: stedi-prod-nodeport
spec:
  selector:
    app: stedi-prod
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-prod-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: stedi-prod-public
    networking.gke.io/managed-certificates: stedi-prod-certificate    
#    kubernetes.io/ingress.allow-http: "false"
    # the below line wasn't there before
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: stedi-prod-frontend-config
spec:
  defaultBackend:
    service:
      name: stedi-prod-nodeport
      port:
        number: 80
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: stedi-prod-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---            
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-prod-certificate
spec:
  domains:
    - stedi.me
    
